# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ansower',
            new_name='Answer',
        ),
        migrations.AlterField(
            model_name='questions',
            name='caption',
            field=models.CharField(max_length=32, verbose_name='问题题目'),
        ),
    ]
